FROM golang:1.22.1-alpine AS build

RUN apk add python3 tzdata
RUN go install github.com/cosmtrek/air@latest
WORKDIR /app/src

COPY src/email_service/*.py /email_service/
COPY src/email_service/requirements.txt /email_service/
WORKDIR /email_service
RUN python3 -m venv venv
RUN venv/bin/python -m pip install -r requirements.txt

ENV SITE_TIMESTAMP="main_0974a43_03/27/24 22:43:17"

WORKDIR /app/src