# compose file for development containers only.
version: '3.8'

services:

  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=app-db-password
      - POSTGRES_USER=app-db-user
      - POSTGRES_DB=app-db
    container_name: backend-db
    hostname: db
    networks:
      - app-net
    ports:
      - 5432:5432
    volumes:
      - backend-db:/var/lib/postgresql/data

  backend:
    restart: on-failure
    ports:
      - 5000:5000
    depends_on:
      - db
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    # env_file:
    #   # contains azure email service ids
    #   - secret.env
    environment:
      # don't really send emails; backend is localhost
      - DEFAULT_ADMIN_EMAIL=user@gmail.com
      - DEFAULT_ADMIN_PASSWORD=password
      - DEFAULT_ADMIN_USERNAME=user
      - DEBUG=true
      - PORT=5000
      - DATABASE_URL=postgres://app-db-user:app-db-password@db:5432/app-db
      - REFRESH_SECRET=somesecretrefreshtoken
      - SECRET=somesecretjwttoken
      - DROP_TABLES=true
      - IS_DEBUG=true

    command: sh -c "air && go build main.go && ./main"
    networks:
      - app-net

  frontend:
    restart: on-failure
    build:
      context: plantmindr
      dockerfile: Dockerfile.dev
    image: frontend
    ports:
      - 4200:4200
    volumes:
      - ./plantmindr:/app
    networks:
      - app-net
    # command: sh -c "rm -rf node_modules && npm install && npm start"
    command: sh -c "npm install && npm start"

volumes:
  backend-db:


networks:
  app-net:
    driver: bridge
