apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-website
  template:
    metadata:
      labels:
        app: static-website
    spec:
      containers:
      - name: static-website
        image: mcoronistestacr3.azurecr.io/aks-test/plantmindr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-website
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: static-website
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static-website
spec:
  ingressClassName: nginx
  rules:
  # - host: mysite2.com
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: static-website
            port:
              number: 80