apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website-backend
  # TODO: this may be redundant
  labels: 
    azure.workload.identity/use: "true"
spec:
  # TODO: this may be redundant
  serviceAccountName: akskvidentityserviceaccount
  replicas: 1
  selector:
    matchLabels:
      app: static-website-backend
  template:
    metadata:
      labels:
        app: static-website-backend
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: akskvidentityserviceaccount
      containers:
        - name: static-website-backend
          image: mcoronistestacr3.azurecr.io/aks-test/plantmindr-backend:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "80"
            # TODO: remove this
            - name: FOO
              value: BAR
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-website-backend
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: static-website-backend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static-website-backend
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: static-website-backend
                port:
                  number: 80
